# Dependencies
markdown:           kramdown
highlighter:        rouge

# Permalinks
permalink:          pretty

# Paginate
paginate:           5
paginate_path:      '/page/:num/'

# Setup
title:              'Zoilo Mora'
tagline:            'Knowledge Base'
description:        'Senior PHP Developer'

url:                'https://zoilomora.net'
baseurl:            ''

author:
  name:             'Zoilo Mora'
  url:              'https://twitter.com/ZoiloMora'

excerpt_separator:  '<!--more-->'

exclude:
  - docker
  - vendor
  - CNAME
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - README.md
